route:
  receiver: ntfy
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: ntfy
    webhook_configs:
      - url: 'http://192.168.32.2:80/homelab-alerts'
        send_resolved: true
