services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - default
      - ntfy_default
      - monitoring_default

networks:
  ntfy_default:
    external: true
  monitoring_default:
    external: true
