services:
  ntfy:
    image: binwiederhier/ntfy:v2.28.0
    container_name: ntfy
    command: serve
    restart: unless-stopped
    ports:
      - "8095:80"
    volumes:
      - /home/joe/ntfy/cache:/var/cache/ntfy
      - /home/joe/ntfy/data:/var/lib/ntfy
    environment:
      - TZ=America/New_York
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.32.0/20
