[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = oKYsCfkTMMccsm7UEiVE676+TieY2z9DLJMmQJShbmE=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_phone
PublicKey = WLViWvs0EGoCL/lbtPHRAji/FfcKawi2FVEhf2EFVCE=
PresharedKey = V4P1kpsOVdi62rL+WTrPgD1nIA95Zi0VC++Cw2+SmOU=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer_macbook
PublicKey = 2n5ra+z4Jh1VisuVPN62GKIY7GRRJyZCZ2qj+kEFsig=
PresharedKey = C7rsNQuObC3iGNX0I5tkD3J7yuVEE+7klsIkC/XOgh8=
AllowedIPs = 10.13.13.3/32

[Peer]
# peer_laptop
PublicKey = 1TWxhqAlv544m9kGnu/F+i0iJM4a7IbpjX5Lg67uYwU=
PresharedKey = efz2qBBFpo6LOTHobli0ajY27Wo3ZMrZs4HeRsCvyk4=
AllowedIPs = 10.13.13.4/32

