services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.18.0
    container_name: woodpecker-server
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9001:9000'
    dns:
      - 192.168.4.2
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST=https://woodpecker.josephbernal.com
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://gitea.josephbernal.com
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    volumes:
      - /home/joe/woodpecker/data:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.18.0
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    dns:
      - 192.168.4.2
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
