services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9001:9000'
    dns:
      - 10.0.0.2
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST=https://woodpecker.josephbernal.com
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://gitea.josephbernal.com
      - WOODPECKER_GITEA_CLIENT=YOUR_GITEA_CLIENT_ID
      - WOODPECKER_GITEA_SECRET=YOUR_GITEA_CLIENT_SECRET
      - WOODPECKER_AGENT_SECRET=YOUR_AGENT_SECRET
    volumes:
      - ./data:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    dns:
      - 10.0.0.2
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=YOUR_AGENT_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
