[Interface]
Address = 10.13.13.4
PrivateKey = aFvS93aDsoXwJVaaL68n+OPurY/qsJbzChezyjEkNlY=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mx7aN5GoWNjIPyIQdTHkGPciXnh/I+IubOfNPf7b7wY=
PresharedKey = efz2qBBFpo6LOTHobli0ajY27Wo3ZMrZs4HeRsCvyk4=
Endpoint = 73.57.142.189:51820
AllowedIPs = 0.0.0.0/0, ::/0
