theme: dark

server:
  address: 'tcp://:9091'

log:
  level: info

totp:
  issuer: josephbernal.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: '*.josephbernal.com'
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: josephbernal.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
