services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "extra/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '3001:3001'
    volumes:
      - /home/joe/uptime-kuma/data:/app/data
    dns:
      - 192.168.4.2
