services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20260223-r0-ls121
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=vpn.josephbernal.com
      - SERVERPORT=51820
      - PEERS=phone,macbook,laptop
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    ports:
      - 51820:51820/udp
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 192.168.4.2
    restart: unless-stopped
