[Interface]
Address = 10.13.13.3
PrivateKey = OMT8iQmSSMhSqXqqzdNBnQLretF30rVfs2o39H3D0Gc=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mx7aN5GoWNjIPyIQdTHkGPciXnh/I+IubOfNPf7b7wY=
PresharedKey = C7rsNQuObC3iGNX0I5tkD3J7yuVEE+7klsIkC/XOgh8=
Endpoint = 73.57.142.189:51820
AllowedIPs = 0.0.0.0/0, ::/0
